services:
  backend:
    build: ./backend
    command: ["nodemon", "--legacy-watch", "src/index.js"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
  
volumes:
  mongodb_data: